CREATE DATABASE Huong_Nguyen_Thi_Thanh_6513124_DB_QLBH
GO
USE Huong_Nguyen_Thi_Thanh_6513124_DB_QLBH
GO

-- ====== BẢNG TỈNH ======
CREATE TABLE Tinh(
	MaTinh TinyInt PRIMARY KEY NOT NULL,
	TenTinh NVARCHAR(90) NOT NULL
);

-- ====== BẢNG XÃ ======
CREATE TABLE Xa(
	MaXa TinyInt PRIMARY KEY NOT NULL,
	TenXa NVARCHAR(90) NOT NULL,
	MaTinh TinyInt NOT NULL,
	CONSTRAINT FK_Xa_Tinh FOREIGN KEY (MaTinh) REFERENCES Tinh(MaTinh) ON DELETE CASCADE
);

-- ====== NHÀ CUNG CẤP ======
CREATE TABLE NhaCC (
    MaNCC VARCHAR(10) PRIMARY KEY NOT NULL,
    TenNCC NVARCHAR(100) NOT NULL,
    DienThoaiNCC VARCHAR(15) NOT NULL,
    EmailNCC VARCHAR(100) NULL,
	DiaChiNCC NVARCHAR(255) NOT NULL
);

-- ====== ĐƠN MUA HÀNG ======
CREATE TABLE DonMuaHang(
	MaDMH CHAR(11) NOT NULL PRIMARY KEY,
	NgayMH Date NOT NULL,
	MaNCC VARCHAR(10) NOT NULL,
	CONSTRAINT FK_DonMuaHang_NhaCC FOREIGN KEY (MaNCC) REFERENCES NhaCC(MaNCC) ON DELETE CASCADE
);

-- ====== KHÁCH HÀNG ======
CREATE TABLE KhachHang(
	MaKH VARCHAR(10) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(50) NOT NULL,
	DienThoaiKH VARCHAR(10) NOT NULL,
	EmailKH VARCHAR(255) NOT NULL,
	DiaChiKH NVARCHAR(255) NOT NULL
);

-- ====== ĐƠN BÁN HÀNG ======
CREATE TABLE DonBanHang(
	MaDBH CHAR(11) NOT NULL PRIMARY KEY,
	NgayBH Date NOT NULL,
	MaKH VARCHAR(10) NOT NULL,
	CONSTRAINT FK_DonBanHang_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH) ON DELETE CASCADE
);

-- ====== LOẠI SẢN PHẨM ======
CREATE TABLE LoaiSP(
	MaLoai VARCHAR(10) NOT NULL PRIMARY KEY,
	TenLSP NVARCHAR(50) NOT NULL
);

-- ====== SẢN PHẨM ======
CREATE TABLE SanPham(
	MaSP VARCHAR(10) NOT NULL PRIMARY KEY,
	TenSP NVARCHAR(50) NOT NULL,
	DonGia Money NOT NULL,
	MoTaSP Text NOT NULL,
	AnhMH NVARCHAR(50) NOT NULL,
	MaLoai VARCHAR(10) NOT NULL,
	CONSTRAINT FK_SanPham_LoaiSP FOREIGN KEY (MaLoai) REFERENCES LoaiSP(MaLoai) ON DELETE CASCADE
);

-- ====== CHI TIẾT MUA HÀNG ======
CREATE TABLE CTMH(
	MaDMH CHAR(11) NOT NULL,
	MaSP VARCHAR(10) NOT NULL, 
	SLM int NOT NULL,
	DGM Money NOT NULL,
	CONSTRAINT PK_CTMH PRIMARY KEY(MaDMH, MaSP),
	CONSTRAINT FK_CTMH_DonMuaHang FOREIGN KEY (MaDMH) REFERENCES DonMuaHang(MaDMH) ON DELETE CASCADE,
	CONSTRAINT FK_CTMH_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);

-- ====== CHI TIẾT BÁN HÀNG ======
CREATE TABLE CTBH(
	MaDBH CHAR(11) NOT NULL,
	MaSP VARCHAR(10) NOT NULL, 
	SLB int NOT NULL,
	DGB Money NOT NULL,
	CONSTRAINT PK_CTBH PRIMARY KEY(MaDBH, MaSP),
	CONSTRAINT FK_CTBH_DonBanHang FOREIGN KEY (MaDBH) REFERENCES DonBanHang(MaDBH) ON DELETE CASCADE,
	CONSTRAINT FK_CTBH_SanPham FOREIGN KEY (MaSP) REFERENCES SanPham(MaSP) ON DELETE CASCADE
);

-- ====== NHÓM SẢN PHẨM ======
CREATE TABLE NhomSP(
	MaNhom VARCHAR(10) PRIMARY KEY NOT NULL,
	TenNhom NVARCHAR(100) NOT NULL
);

-- Cập nhật bảng LOẠI SẢN PHẨM thêm khóa ngoại
ALTER TABLE LoaiSP
ADD MaNhom VARCHAR(10) NOT NULL
	CONSTRAINT FK_LoaiSP_NhomSP FOREIGN KEY (MaNhom)
	REFERENCES NhomSP(MaNhom) ON DELETE CASCADE;

-- ====== GIAN HÀNG ======
CREATE TABLE GianHang(
	MaGH VARCHAR(10) PRIMARY KEY NOT NULL,
	TenGH NVARCHAR(100) NOT NULL,
	MoTaGH NVARCHAR(255) NULL,
	NgayTao DATE NOT NULL DEFAULT GETDATE(),
	DienThoaiGH VARCHAR(15) NOT NULL,
    EmailGH VARCHAR(100) NULL,
    DiaChiGH NVARCHAR(200) NOT NULL
);
