CREATE OR ALTER PROC sp_CTBH_Insert
    @MaDBH CHAR(11),
    @MaSP VARCHAR(10),
    @SLM INT,
    @DGM MONEY
AS
BEGIN
    INSERT INTO CTBH (MaDBH, MaSP, SLM, DGM)
    VALUES (@MaDBH, @MaSP, @SLM, @DGM);
END;
GO

CREATE OR ALTER PROC sp_CTBH_Update
    @MaDBH CHAR(11),
    @MaSP VARCHAR(10),
    @SLM INT,
    @DGM MONEY
AS
BEGIN
    UPDATE CTBH
    SET SLM = @SLM,
        DGM = @DGM
    WHERE MaDBH = @MaDBH AND MaSP = @MaSP;
END;
GO

CREATE OR ALTER PROC sp_CTBH_GetAll AS SELECT * FROM CTBH; 
GO
CREATE OR ALTER PROC sp_CTBH_GetById @MaDBH CHAR(11), @MaSP VARCHAR(10)
AS SELECT * FROM CTBH WHERE MaDBH = @MaDBH AND MaSP = @MaSP;
GO
CREATE OR ALTER PROC sp_CTBH_Delete @MaDBH CHAR(11), @MaSP VARCHAR(10)
AS DELETE FROM CTBH WHERE MaDBH = @MaDBH AND MaSP = @MaSP; 
GO
