USE Huong_Nguyen_Thi_Thanh_6513124_DB_QLBH;
GO
CREATE OR ALTER PROC sp_CTBH_Insert
    @MaDBH CHAR(11),
    @MaSP VARCHAR(10),
    @SLB INT,
    @DGB MONEY
AS
BEGIN
    INSERT INTO CTBH (MaDBH, MaSP, SLB, DGB)
    VALUES (@MaDBH, @MaSP, @SLB, @DGB);
END;
GO

CREATE OR ALTER PROC sp_CTBH_Update
    @MaDBH CHAR(11),
    @MaSP VARCHAR(10),
    @SLB INT,
    @DGB MONEY
AS
BEGIN
    UPDATE CTBH
    SET SLB = @SLB,
        DGB = @DGB
    WHERE MaDBH = @MaDBH AND MaSP = @MaSP;
END;
GO

CREATE OR ALTER PROC sp_CTBH_GetAll AS SELECT * FROM CTBH; 
GO
CREATE OR ALTER PROC sp_CTBH_GetById @MaDBH CHAR(11), @MaSP VARCHAR(10)
AS SELECT * FROM CTBH WHERE MaDBH = @MaDBH AND MaSP = @MaSP;
GO
CREATE OR ALTER PROC sp_CTBH_Delete @MaDBH CHAR(11), @MaSP VARCHAR(10)
AS DELETE FROM CTBH WHERE MaDBH = @MaDBH AND MaSP = @MaSP; 
GO

CREATE OR ALTER PROC sp_CTBH_GetAll_Detail AS SELECT C.*, S.TenSP FROM CTBH C JOIN SanPham S ON S.MaSP=C.MaSP;
GO
CREATE OR ALTER PROC sp_CTBH_GetById_Detail @MaDBH CHAR(11), @MaSP VARCHAR(10)
AS SELECT C.*, S.TenSP FROM CTBH C JOIN SanPham S ON S.MaSP=C.MaSP WHERE C.MaDBH = @MaDBH AND S.MaSP = @MaSP;
GO
