USE Huong_Nguyen_Thi_Thanh_6513124_DB_QLBH;
GO

-- Dùng cho insert nhiều dòng chi tiết
CREATE TYPE CTMH_List AS TABLE
(
    MaSP VARCHAR(10),
    SLM INT,
    DGM MONEY
);
GO
CREATE OR ALTER PROC sp_CTMH_Insert
    @MaDMH CHAR(11),
    @MaSP VARCHAR(10),
    @SLM INT,
    @DGM MONEY
AS
BEGIN
    INSERT INTO CTMH (MaDMH, MaSP, SLM, DGM)
    VALUES (@MaDMH, @MaSP, @SLM, @DGM);
END
GO

CREATE OR ALTER PROC sp_CTMH_Insert_Multi
(
    @MaDMH CHAR(11),
    @ChiTiet CTMH_List READONLY
)
AS
BEGIN
    INSERT INTO CTMH(MaDMH, MaSP, SLM, DGM)
    SELECT @MaDMH, MaSP, SLM, DGM FROM @ChiTiet;
END;
GO


CREATE OR ALTER PROC sp_CTMH_Update
    @MaDMH CHAR(11),
    @MaSP VARCHAR(10),
    @SLM INT,
    @DGM MONEY
AS
BEGIN
    UPDATE CTMH
    SET SLM = @SLM,
        DGM = @DGM
    WHERE MaDMH = @MaDMH AND MaSP = @MaSP;
END;
GO

CREATE OR ALTER PROC sp_CTMH_GetAll AS SELECT * FROM CTMH; 
GO

CREATE OR ALTER PROC sp_CTMH_GetAll_Detail AS SELECT C.MaDMH, C.MaSP, S.TenSP, C.DGM, C.SLM FROM CTMH C JOIN SanPham S ON S.MaSP=C.MaSP; 
GO

CREATE OR ALTER PROC sp_CTMH_GetById @MaDMH CHAR(11), @MaSP VARCHAR(10)
AS SELECT * FROM CTMH WHERE MaDMH = @MaDMH AND MaSP = @MaSP;
GO

CREATE OR ALTER PROC sp_CTMH_GetById_Detail 
	@MaDMH CHAR(11), @MaSP VARCHAR(10)
	AS SELECT C.MaDMH, C.MaSP, S.TenSP, C.DGM, C.SLM FROM CTMH C JOIN SanPham S ON S.MaSP=C.MaSP
	WHERE C.MaDMH = @MaDMH AND C.MaSP = @MaSP;
GO

CREATE OR ALTER PROC sp_CTMH_Delete @MaDMH CHAR(11), @MaSP VARCHAR(10)
AS DELETE FROM CTMH WHERE MaDMH = @MaDMH AND MaSP = @MaSP;
GO

CREATE OR ALTER PROC sp_CTMH_GetAllByDMH
(
    @MaDMH CHAR(11)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT c.*, sp.TenSP
    FROM CTMH c
    LEFT JOIN SanPham sp ON c.MaSP = sp.MaSP
    WHERE c.MaDMH = @MaDMH;
END
