CREATE OR ALTER PROC sp_CTMH_Insert
    @MaDMH CHAR(11),
    @MaSP VARCHAR(10),
    @SLM INT,
    @DGM MONEY
AS
BEGIN
    INSERT INTO CTMH (MaDMH, MaSP, SLM, DGM)
    VALUES (@MaDMH, @MaSP, @SLM, @DGM);
END
GO

CREATE OR ALTER PROC sp_CTMH_Update
    @MaDMH CHAR(11),
    @MaSP VARCHAR(10),
    @SLM INT,
    @DGM MONEY
AS
BEGIN
    UPDATE CTMH
    SET SLM = @SLM,
        DGM = @DGM
    WHERE MaDMH = @MaDMH AND MaSP = @MaSP;
END;
GO

CREATE OR ALTER PROC sp_CTMH_GetAll AS SELECT * FROM CTMH; 
GO
CREATE OR ALTER PROC sp_CTMH_GetById @MaDMH CHAR(11), @MaSP VARCHAR(10)
AS SELECT * FROM CTMH WHERE MaDMH = @MaDMH AND MaSP = @MaSP;
GO
CREATE OR ALTER PROC sp_CTMH_Delete @MaDMH CHAR(11), @MaSP VARCHAR(10)
AS DELETE FROM CTMH WHERE MaDMH = @MaDMH AND MaSP = @MaSP;
GO