CREATE OR ALTER PROC sp_GianHang_Insert(@TenGH NVARCHAR(100), @MoTaGH NVARCHAR(255), @MaNCC VARCHAR(10))
AS
BEGIN
    DECLARE @Count INT = (SELECT COUNT(*) + 1 FROM GianHang);
    DECLARE @MaGH VARCHAR(10) = 'GH' + RIGHT('00' + CAST(@Count AS VARCHAR(2)), 2);
    INSERT INTO GianHang(MaGH, TenGH, MoTaGH, NgayTao, MaNCC)
    VALUES(@MaGH, @TenGH, @MoTaGH, GETDATE(), @MaNCC);
END
GO

CREATE OR ALTER PROC sp_GianHang_Update(@MaGH VARCHAR(10), @TenGH NVARCHAR(100), @MoTaGH NVARCHAR(255), @MaNCC VARCHAR(10))
AS
BEGIN
    UPDATE GianHang SET TenGH=@TenGH, MoTaGH=@MoTaGH, MaNCC=@MaNCC WHERE MaGH=@MaGH;
END
GO

CREATE OR ALTER PROC sp_GianHang_GetAll AS SELECT * FROM GianHang; 
GO
CREATE OR ALTER PROC sp_GianHang_GetByID(@MaGH VARCHAR(10)) AS SELECT * FROM GianHang WHERE MaGH=@MaGH;
GO
CREATE OR ALTER PROC sp_GianHang_Delete(@MaGH VARCHAR(10)) AS DELETE FROM GianHang WHERE MaGH=@MaGH;
GO
