CREATE OR ALTER PROC sp_LoaiSP_Insert(@TenLSP NVARCHAR(50), @MaNhom VARCHAR(10))
AS
BEGIN
    DECLARE @Count INT = (SELECT COUNT(*) + 1 FROM LoaiSP);
    DECLARE @MaLoai VARCHAR(10) = 'LSP' + RIGHT('00' + CAST(@Count AS VARCHAR(2)), 2);
    INSERT INTO LoaiSP VALUES(@MaLoai, @TenLSP, @MaNhom);
END
GO

CREATE OR ALTER PROC sp_LoaiSP_Update(@MaLoai VARCHAR(10), @TenLSP NVARCHAR(50), @MaNhom VARCHAR(10))
AS
BEGIN
    UPDATE LoaiSP SET TenLSP=@TenLSP, MaNhom=@MaNhom WHERE MaLoai=@MaLoai;
END
GO

CREATE OR ALTER PROC sp_LoaiSP_GetAll AS SELECT * FROM LoaiSP; 
GO
CREATE OR ALTER PROC sp_LoaiSP_GetByID(@MaLoai VARCHAR(10)) AS SELECT * FROM LoaiSP WHERE MaLoai=@MaLoai; 
GO
CREATE OR ALTER PROC sp_LoaiSP_Delete(@MaLoai VARCHAR(10)) AS DELETE FROM LoaiSP WHERE MaLoai=@MaLoai; 
GO
