CREATE OR ALTER PROC sp_NhaCC_Insert
(@TenNCC NVARCHAR(100), @DienThoaiNCC VARCHAR(15), @EmailNCC VARCHAR(100),
 @DiaChiNCC NVARCHAR(200), @MaXa TINYINT)
AS
BEGIN
    DECLARE @Count INT = (SELECT COUNT(*) + 1 FROM NhaCC);
    DECLARE @MaNCC VARCHAR(10) = 'NCC' + RIGHT('0000000' + CAST(@Count AS VARCHAR(2)), 2);

    INSERT INTO NhaCC VALUES(@MaNCC, @TenNCC, @DienThoaiNCC, @EmailNCC, @DiaChiNCC, @MaXa);
END
GO

CREATE OR ALTER PROC sp_NhaCC_Update
(@MaNCC VARCHAR(10), @TenNCC NVARCHAR(100), @DienThoaiNCC VARCHAR(15),
 @EmailNCC VARCHAR(100), @DiaChiNCC NVARCHAR(200), @MaXa TINYINT)
AS
BEGIN
    UPDATE NhaCC
    SET TenNCC=@TenNCC, DienThoaiNCC=@DienThoaiNCC, EmailNCC=@EmailNCC, DiaChiNCC=@DiaChiNCC, MaXa=@MaXa
    WHERE MaNCC=@MaNCC;
END
GO

CREATE OR ALTER PROC sp_NhaCC_GetAll AS SELECT * FROM NhaCC; 
GO
CREATE OR ALTER PROC sp_NhaCC_GetByID(@MaNCC VARCHAR(10)) AS SELECT * FROM NhaCC WHERE MaNCC=@MaNCC; 
GO
CREATE OR ALTER PROC sp_NhaCC_Delete(@MaNCC VARCHAR(10)) AS DELETE FROM NhaCC WHERE MaNCC=@MaNCC; 
GO
