CREATE OR ALTER PROC sp_NhomSP_Insert(@TenNhom NVARCHAR(100))
AS
BEGIN
    DECLARE @Count INT = (SELECT COUNT(*) + 1 FROM NhomSP);
    DECLARE @MaNhom VARCHAR(10) = 'NSP' + RIGHT('0000000' + CAST(@Count AS VARCHAR(2)), 7);
    INSERT INTO NhomSP VALUES(@MaNhom, @TenNhom);
END
GO

CREATE OR ALTER PROC sp_NhomSP_Update(@MaNhom VARCHAR(10), @TenNhom NVARCHAR(100))
AS
BEGIN
    UPDATE NhomSP SET TenNhom=@TenNhom WHERE MaNhom=@MaNhom;
END
GO

CREATE OR ALTER PROC sp_NhomSP_GetAll AS SELECT * FROM NhomSP;
GO
CREATE OR ALTER PROC sp_NhomSP_GetByID(@MaNhom VARCHAR(10)) AS SELECT * FROM NhomSP WHERE MaNhom=@MaNhom; 
GO
CREATE OR ALTER PROC sp_NhomSP_Delete(@MaNhom VARCHAR(10)) AS DELETE FROM NhomSP WHERE MaNhom=@MaNhom; 
GO
