CREATE OR ALTER PROC sp_SanPham_Insert
(@TenSP NVARCHAR(50), @DonGia MONEY, @MoTaSP TEXT, @AnhMH NVARCHAR(50), @MaLoai VARCHAR(10))
AS
BEGIN
    DECLARE @Count INT = (SELECT COUNT(*) + 1 FROM SanPham);
    DECLARE @MaSP VARCHAR(10) = 'SP' + RIGHT('00000000' + CAST(@Count AS VARCHAR(2)), 8);
    INSERT INTO SanPham VALUES(@MaSP, @TenSP, @DonGia, @MoTaSP, @AnhMH, @MaLoai);
END
GO

CREATE OR ALTER PROC sp_SanPham_Update
(@MaSP VARCHAR(10), @TenSP NVARCHAR(50), @DonGia MONEY, @MoTaSP TEXT, @AnhMH NVARCHAR(50), @MaLoai VARCHAR(10))
AS
BEGIN
    UPDATE SanPham
    SET TenSP=@TenSP, DonGia=@DonGia, MoTaSP=@MoTaSP, AnhMH=@AnhMH, MaLoai=@MaLoai
    WHERE MaSP=@MaSP;
END
GO

CREATE OR ALTER PROC sp_SanPham_GetAll AS SELECT * FROM SanPham; 
GO
CREATE OR ALTER PROC sp_SanPham_GetByID(@MaSP VARCHAR(10)) AS SELECT * FROM SanPham WHERE MaSP=@MaSP;
GO
CREATE OR ALTER PROC sp_SanPham_Delete(@MaSP VARCHAR(10)) AS DELETE FROM SanPham WHERE MaSP=@MaSP; 
GO
