CREATE OR ALTER PROC sp_SanPham_Insert
(@TenSP NVARCHAR(50), @DonGia MONEY, @MoTaSP TEXT, @AnhMH NVARCHAR(50), @MaLoai VARCHAR(10), @MaGH VARCHAR(10) = NULL)
AS
BEGIN
    DECLARE @Count INT = (SELECT COUNT(*) + 1 FROM SanPham);
    DECLARE @MaSP VARCHAR(10) = 'SP' + RIGHT('00' + CAST(@Count AS VARCHAR(2)), 2);
    INSERT INTO SanPham VALUES(@MaSP, @TenSP, @DonGia, @MoTaSP, @AnhMH, @MaLoai, @MaGH);
END
GO

CREATE OR ALTER PROC sp_SanPham_Update
(@MaSP VARCHAR(10), @TenSP NVARCHAR(50), @DonGia MONEY, @MoTaSP TEXT, @AnhMH NVARCHAR(50), @MaLoai VARCHAR(10), @MaGH VARCHAR(10))
AS
BEGIN
    UPDATE SanPham
    SET TenSP=@TenSP, DonGia=@DonGia, MoTaSP=@MoTaSP, AnhMH=@AnhMH, MaLoai=@MaLoai, MaGH=@MaGH
    WHERE MaSP=@MaSP;
END
GO

CREATE OR ALTER PROC sp_SanPham_GetAll AS SELECT * FROM SanPham; 
GO
CREATE OR ALTER PROC sp_SanPham_GetByID(@MaSP VARCHAR(10)) AS SELECT * FROM SanPham WHERE MaSP=@MaSP;
GO
CREATE OR ALTER PROC sp_SanPham_Delete(@MaSP VARCHAR(10)) AS DELETE FROM SanPham WHERE MaSP=@MaSP; 
GO
