CREATE OR ALTER PROC sp_Xa_Insert
(@TenXa NVARCHAR(90), @MaTinh TINYINT)
AS
BEGIN
    DECLARE @MaXa TINYINT = (SELECT ISNULL(MAX(MaXa), 0) + 1 FROM Xa);
    INSERT INTO Xa VALUES(@MaXa, @TenXa, @MaTinh);
END;
GO

CREATE OR ALTER PROC sp_Xa_Update
(@MaXa TINYINT, @TenXa NVARCHAR(90), @MaTinh TINYINT)
AS
BEGIN
    UPDATE Xa SET TenXa = @TenXa, MaTinh = @MaTinh WHERE MaXa = @MaXa;
END;
GO

CREATE OR ALTER PROC sp_Xa_GetAll AS SELECT * FROM Xa; 
GO
CREATE OR ALTER PROC sp_Xa_GetByID(@MaXa TINYINT) AS SELECT * FROM Xa WHERE MaXa=@MaXa; 
GO
CREATE OR ALTER PROC sp_Xa_Delete(@MaXa TINYINT) AS DELETE FROM Xa WHERE MaXa=@MaXa; 
GO
